# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m

# AndroidX
android.useAndroidX=true
android.enableJetifier=true

# 只構建 arm64 加快速度
reactNativeArchitectures=arm64-v8a

# New Architecture - DISABLE for BLE/Geolocation compatibility
newArchEnabled=false

# Hermes
hermesEnabled=true
